/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DonutsRouteRouteImport } from './routes/donuts/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonutsIndexRouteImport } from './routes/donuts/index'

const DonutsRouteRoute = DonutsRouteRouteImport.update({
  id: '/donuts',
  path: '/donuts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonutsIndexRoute = DonutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DonutsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donuts': typeof DonutsRouteRouteWithChildren
  '/donuts/': typeof DonutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donuts': typeof DonutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donuts': typeof DonutsRouteRouteWithChildren
  '/donuts/': typeof DonutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/donuts' | '/donuts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/donuts'
  id: '__root__' | '/' | '/donuts' | '/donuts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonutsRouteRoute: typeof DonutsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/donuts': {
      id: '/donuts'
      path: '/donuts'
      fullPath: '/donuts'
      preLoaderRoute: typeof DonutsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donuts/': {
      id: '/donuts/'
      path: '/'
      fullPath: '/donuts/'
      preLoaderRoute: typeof DonutsIndexRouteImport
      parentRoute: typeof DonutsRouteRoute
    }
  }
}

interface DonutsRouteRouteChildren {
  DonutsIndexRoute: typeof DonutsIndexRoute
}

const DonutsRouteRouteChildren: DonutsRouteRouteChildren = {
  DonutsIndexRoute: DonutsIndexRoute,
}

const DonutsRouteRouteWithChildren = DonutsRouteRoute._addFileChildren(
  DonutsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonutsRouteRoute: DonutsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
